FROM ubuntu:22.04
RUN apt-get update -q && \
    apt-get install -y -q lua5.4 lua5.4-dev luarocks && \
    luarocks --lua-version 5.4 install busted
WORKDIR /addon
CMD ["busted", "--pattern", "_test", "tests/"]
