dofile("tests/mock_wow_api.lua")
loadfile("Core/Themes.lua")("WhatTodo", _G.WhatTodo)
loadfile("Core/DisplaySettings.lua")("WhatTodo", _G.WhatTodo)

local DisplaySettings = _G.WhatTodo.DisplaySettings

describe("DisplaySettings.Normalize — valeurs valides", function()
    it("conserve des réglages déjà valides", function()
        local out = DisplaySettings.Normalize({ scale = 1.5, backgroundAlpha = 0.4, locked = true })
        assert.equals(1.5, out.scale)
        assert.equals(0.4, out.backgroundAlpha)
        assert.is_true(out.locked)
    end)

    it("les valeurs par défaut sont elles-mêmes valides", function()
        local out = DisplaySettings.Normalize(DisplaySettings.DEFAULTS)
        assert.equals(DisplaySettings.DEFAULTS.scale, out.scale)
        assert.equals(DisplaySettings.DEFAULTS.backgroundAlpha, out.backgroundAlpha)
        assert.equals(DisplaySettings.DEFAULTS.locked, out.locked)
    end)

    it("renvoie une nouvelle table sans modifier l'entrée", function()
        local raw = { scale = 99, backgroundAlpha = 0.5, locked = false }
        local out = DisplaySettings.Normalize(raw)
        assert.are_not.equal(raw, out)
        assert.equals(99, raw.scale)
    end)
end)

describe("DisplaySettings.Normalize — échelle", function()
    it("borne une échelle trop grande au maximum", function()
        assert.equals(DisplaySettings.SCALE_MAX, DisplaySettings.Normalize({ scale = 10 }).scale)
    end)

    it("borne une échelle trop petite au minimum", function()
        assert.equals(DisplaySettings.SCALE_MIN, DisplaySettings.Normalize({ scale = 0.1 }).scale)
    end)

    it("remplace une échelle absente, non numérique ou NaN par la valeur par défaut", function()
        assert.equals(1, DisplaySettings.Normalize({}).scale)
        assert.equals(1, DisplaySettings.Normalize({ scale = "big" }).scale)
        assert.equals(1, DisplaySettings.Normalize({ scale = 0 / 0 }).scale)
    end)
end)

describe("DisplaySettings.Normalize — opacité du fond", function()
    it("borne l'opacité entre 0 et 1", function()
        assert.equals(0, DisplaySettings.Normalize({ backgroundAlpha = -1 }).backgroundAlpha)
        assert.equals(1, DisplaySettings.Normalize({ backgroundAlpha = 3 }).backgroundAlpha)
    end)

    it("remplace une opacité non numérique par la valeur par défaut", function()
        assert.equals(1, DisplaySettings.Normalize({ backgroundAlpha = true }).backgroundAlpha)
    end)
end)

describe("DisplaySettings.Normalize — verrou", function()
    it("ne considère comme verrouillé que le booléen true", function()
        assert.is_false(DisplaySettings.Normalize({ locked = "yes" }).locked)
        assert.is_false(DisplaySettings.Normalize({ locked = 1 }).locked)
        assert.is_false(DisplaySettings.Normalize({}).locked)
    end)
end)

describe("DisplaySettings.Normalize — entrée invalide", function()
    it("lève une erreur si les réglages ne sont pas une table", function()
        assert.has_error(function() DisplaySettings.Normalize(nil) end)
        assert.has_error(function() DisplaySettings.Normalize("scale=1") end)
    end)
end)

describe("DisplaySettings.Normalize — rendu des tâches faites", function()
    it("conserve un style connu", function()
        assert.equals("show", DisplaySettings.Normalize({ completedStyle = "show" }).completedStyle)
        assert.equals("dim", DisplaySettings.Normalize({ completedStyle = "dim" }).completedStyle)
        assert.equals("hide", DisplaySettings.Normalize({ completedStyle = "hide" }).completedStyle)
    end)

    it("remplace un style inconnu ou absent par le grisé", function()
        assert.equals("dim", DisplaySettings.Normalize({ completedStyle = "blink" }).completedStyle)
        assert.equals("dim", DisplaySettings.Normalize({}).completedStyle)
    end)
end)

describe("DisplaySettings.Normalize — masquage en combat", function()
    it("ne masque en combat que si le réglage vaut le booléen true", function()
        assert.is_true(DisplaySettings.Normalize({ hideInCombat = true }).hideInCombat)
        assert.is_false(DisplaySettings.Normalize({ hideInCombat = "yes" }).hideInCombat)
        assert.is_false(DisplaySettings.Normalize({}).hideInCombat)
    end)
end)

describe("DisplaySettings.IsListVisible — visibilité effective de la liste", function()
    it("suit l'état affiché/masqué hors combat", function()
        assert.is_true(DisplaySettings.IsListVisible(true, false, true))
        assert.is_false(DisplaySettings.IsListVisible(false, false, true))
    end)

    it("masque la liste en combat quand le réglage est actif", function()
        assert.is_false(DisplaySettings.IsListVisible(true, true, true))
    end)

    it("laisse la liste affichée en combat quand le réglage est inactif", function()
        assert.is_true(DisplaySettings.IsListVisible(true, true, false))
    end)

    it("ne réaffiche jamais en combat une liste masquée par le joueur", function()
        assert.is_false(DisplaySettings.IsListVisible(false, true, false))
    end)
end)
