dofile("tests/mock_wow_api.lua")
-- Core/Reset.lua attend le vararg (ADDON_NAME, WhatTodo) ; on l'injecte via loadfile.
loadfile("Core/Reset.lua")("WhatTodo", _G.WhatTodo)

local Reset = _G.WhatTodo.Reset

describe("Reset.GetWeeklyResetWeekday", function()
    it("US (1) -> mardi (3)", function()
        assert.equals(3, Reset.GetWeeklyResetWeekday(1))
    end)
    it("EU (3) -> mercredi (4)", function()
        assert.equals(4, Reset.GetWeeklyResetWeekday(3))
    end)
    it("KR/TW/CN (2,4,5) -> jeudi (5)", function()
        assert.equals(5, Reset.GetWeeklyResetWeekday(2))
        assert.equals(5, Reset.GetWeeklyResetWeekday(4))
        assert.equals(5, Reset.GetWeeklyResetWeekday(5))
    end)
    it("région inconnue ou nil -> mercredi (4) par défaut", function()
        assert.equals(4, Reset.GetWeeklyResetWeekday(nil))
        assert.equals(4, Reset.GetWeeklyResetWeekday(99))
    end)
end)

describe("Reset.GetResetBoundary weekly par région", function()
    -- offset 0 -> heure royaume = UTC. Le conteneur de test tourne en UTC,
    -- donc os.time (heure locale) == UTC ici. now = vendredi 2026-07-03 12:00 UTC.
    local now = os.time({ year = 2026, month = 7, day = 3, hour = 12, min = 0, sec = 0, isdst = false })

    it("mardi (US) -> borne mardi 2026-06-30 05:00", function()
        local b = Reset.GetResetBoundary("weekly", now, 0, 3)
        assert.equals("06/30", os.date("!%m/%d", b))
        assert.equals(5, os.date("!*t", b).hour)
    end)
    it("mercredi (EU) -> borne mercredi 2026-07-01 05:00", function()
        local b = Reset.GetResetBoundary("weekly", now, 0, 4)
        assert.equals("07/01", os.date("!%m/%d", b))
        assert.equals(5, os.date("!*t", b).hour)
    end)
    it("jeudi (Asie) -> borne jeudi 2026-07-02 05:00", function()
        local b = Reset.GetResetBoundary("weekly", now, 0, 5)
        assert.equals("07/02", os.date("!%m/%d", b))
        assert.equals(5, os.date("!*t", b).hour)
    end)
    it("sans argument -> non-régression mercredi", function()
        local b = Reset.GetResetBoundary("weekly", now, 0)
        assert.equals("07/01", os.date("!%m/%d", b))
    end)
end)
